[package]
name = "tuisky"
version = "0.0.1"
authors = ["sugyan <sugi1982+github@gmail.com>"]
edition = "2021"
rust-version = "1.74"
description = "TUI application for Bluesky"
readme = "README.md"
repository = "https://github.com/sugyan/tuisky"
license = "MIT"
keywords = ["tui", "atproto", "bluesky", "atrium"]

[dependencies]
bsky-sdk = "0.1.3"
chrono = { version = "0.4.38", default-features = false }
clap = { version = "4.5.8", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = { version = "0.27.0", features = ["event-stream"] }
directories = "5.0.1"
futures-util = "0.3.30"
indexmap = "2.2.6"
log = "0.4.21"
ratatui = "0.27.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
textwrap = "0.16.1"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tui-logger = "0.11.2"
tui-prompts = "0.3.13"

[dev-dependencies]
ipld-core = "0.4.0"

[patch.crates-io]
tui-logger = { git = "https://github.com/gin66/tui-logger", rev = "775c759c89a808b6f479b869c533d33b18fe5f44" }

[[bin]]
name = "tuisky"
path = "src/bin/main.rs"
